---
# Ansible Inventory File - EXAMPLE
# Copy to inventory/hosts.yml and update with your actual values

all:
  children:
    nd:
      hosts:
        nexus_dashboard:
          ansible_host: 10.0.0.100  # Your Nexus Dashboard IP

    switches:
      vars:
        ansible_network_os: cisco.nxos.nxos
        ansible_connection: ansible.netcommon.network_cli
        ansible_user: admin
        ansible_password: "{{ vault_switch_password }}"
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: "{{ vault_switch_password }}"
      children:
        aggregation:
          hosts:
            agg01:
              ansible_host: 10.0.1.1
              role: aggregation
              fabric: my-fabric
              add_to_fabric: true
              mgmt_int: Vlan199
              destination_switch_sn: SERIAL123
            agg02:
              ansible_host: 10.0.1.2
              role: aggregation
              fabric: my-fabric
              add_to_fabric: true
              mgmt_int: Vlan199
              destination_switch_sn: SERIAL456
        access:
          hosts:
            access01:
              ansible_host: 10.0.2.1
              role: access
              fabric: my-fabric
              add_to_fabric: true
              mgmt_int: Vlan199
              destination_switch_sn: SERIAL789
              # For POAP (new hardware):
              # destination_switch_model: N9K-C9300v
              # destination_switch_version: "10.6(1)"
