---
# Ansible Inventory File - EXAMPLE
# Copy to inventory/hosts.yml and update with your actual values

all:
  children:
    nd:
      hosts:
        nexus_dashboard:
          ansible_host: 10.0.0.100  # Your Nexus Dashboard IP

    switches:
      vars:
        ansible_network_os: cisco.nxos.nxos
        ansible_connection: ansible.netcommon.network_cli
        ansible_user: admin
        ansible_password: "{{ vault_switch_password }}"
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: "{{ vault_switch_password }}"
      children:
        aggregation:
          hosts:
            # --- Existing switch being migrated to NDFC ---
            # destination_switch_sn is commented out until the serial is confirmed
            # or the switch is live and reachable (serial queried from NDFC after import)
            agg01:
              ansible_host: 10.0.1.1
              role: aggregation
              fabric: my-fabric
              add_to_fabric: true
              mgmt_int: Vlan199         # In-band management interface (classicLan fabrics)
              # DHCP relay servers for management VLAN (for POAP leaf switches)
              # mgmt_int_dhcp_relay_list:
              #   - 10.0.0.100
              # For POAP downstream leaf switches - list VPC IDs that need suspend-individual disabled
              # disable_lacp_suspend_individual_po_list:
              #   - 104
              #   - 105
              #destination_switch_sn: SERIAL123   # Uncomment once serial is known
            agg02:
              ansible_host: 10.0.1.2
              role: aggregation
              fabric: my-fabric
              add_to_fabric: true
              mgmt_int: Vlan199
              # mgmt_int_dhcp_relay_list:
              #   - 10.0.0.100
              # disable_lacp_suspend_individual_po_list:
              #   - 104
              #   - 105
              #destination_switch_sn: SERIAL456   # Uncomment once serial is known
        access:
          hosts:
            # --- Existing switch in an enhancedLan fabric ---
            # mgmt_int is mgmt0 (out-of-band) when INBAND_MGMT: false
            access01:
              ansible_host: 10.0.2.1
              role: access
              fabric: my-fabric
              add_to_fabric: true
              mgmt_int: Vlan199
              #destination_switch_sn: SERIAL789   # Uncomment once serial is known

            # --- New switch (POAP pre-provisioning) ---
            # destination_switch_sn is required for POAP; model and version trigger
            # the bootstrap process via NDFC DHCP/POAP pipeline
            access02-poap:
              ansible_host: 10.0.2.2
              role: access
              fabric: my-fabric
              add_to_fabric: true
              mgmt_int: Vlan199
              destination_switch_sn: SERIALNEW    # Required for POAP
              destination_switch_model: N9K-C9300v # Required for POAP
              destination_switch_version: "10.6(1)" # Required for POAP

            # --- Switch in enhancedLan fabric (out-of-band mgmt) ---
            access03-enhanced:
              ansible_host: 10.0.3.1
              role: access
              fabric: my-enhanced-fabric
              add_to_fabric: true
              mgmt_int: mgmt0           # Out-of-band mgmt port (enhancedLan / INBAND_MGMT: false)
              #destination_switch_sn: SERIAL_ENH   # Uncomment once serial is known
