---
# Ansible-Galaxy Collections requirements file
collections:
  - name: cisco.nd
    version: ">=1.3.0"
  - name: cisco.dcnm
    version: ">=2.4.0"
  - name: community.general
    version: ">=6.4.0"
  - name: cisco.nxos
    version: ">=4.6.0"